services:
  read-service:
    build:
      context: .
      dockerfile: Dockerfile.read-service
    ports:
      - "8080:8080"

  write-service:
    build:
      context: .
      dockerfile: Dockerfile.write-service
    ports:
      - "8081:8080"

  cassandra-db:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=myCluster
    volumes:
      - cassandra-data:/var/lib/cassandra

volumes:
  cassandra-data:
