version: '3.8'  # Always good to specify the version

services:
  read-service:
    build:
      context: .
      dockerfile: Dockerfile.read-service
    ports:
      - "8080:8080"

  write-service:
    build:
      context: .
      dockerfile: Dockerfile.write-service
    ports:
      - "8081:8080"

  cassandra-db:
    image: cassandra:latest
    container_name: cassandra-db
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=myCluster
    volumes:
      - ./init.cql:/docker-entrypoint-initdb.d/init.cql  # Mapping a local file to a container path
      - cassandra-data:/var/lib/cassandra               # Using a named volume

volumes:  # This should be at the same level as 'services'
  cassandra-data:
    driver: local  # Optional: specifying the driver, default is 'local'

